<a href="https://colab.research.google.com/github/witchayapornphr/witchayaporn_phaengbudda/blob/main/683020593_9_%E0%B8%A7%E0%B8%B4%E0%B8%8A%E0%B8%8D%E0%B8%B2%E0%B8%9E%E0%B8%A3_%E0%B9%81%E0%B8%9C%E0%B8%87%E0%B8%9A%E0%B8%B8%E0%B8%94%E0%B8%94%E0%B8%B2_SC612104_Session07_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SC 612 104 Essential Data Science
## NumPy: Array, Shape, Vectorized Operation

**ผู้สอน:** อ.ดร.พิชญา วิรัชโชติเสถียร (Pitchaya Wiratchotisatian)
**ภาควิชาสถิติ คณะวิทยาศาสตร์ มหาวิทยาลัยขอนแก่น**

---

### เนื้อหาใน Notebook นี้

1. ทำไมต้องมี NumPy
2. การสร้าง array
3. Shape และมิติของ array
4. Vectorized Operation
5. การเข้าถึงและ slicing array

**แบบฝึกหัดท้ายเรื่อง**

---
## 1. ทำไมต้องมี NumPy?

ลองดูปัญหานี้: มีคะแนนสอบเก็บใน list (ที่เรียนมาจาก Collections) อยากบวกคะแนนพิเศษ 5 คะแนนให้ทุกคน


In [ ]:
scores = [78, 85, 62, 90, 55]

# วิธีปกติด้วย list - ต้องใช้ loop หรือ comprehension
scores_bonus = [s + 5 for s in scores]
print(scores_bonus)

# ลองบวก list ตรงๆ ดูสิ จะเกิดอะไรขึ้น?
# print(scores + 5)   # ลบ # แล้วรันดู จะเห็น TypeError! list บวกเลขตรงๆไม่ได้

จะเห็นว่า list ธรรมดา**บวกเลขตรงๆไม่ได้** ต้องใช้ comprehension หรือ loop เสมอ — และเมื่อข้อมูลมีขนาดใหญ่ (เช่น คะแนนนักศึกษาทั้งมหาวิทยาลัย 10,000 คน) การใช้ loop จะ**ช้ามาก**

**NumPy** (Numerical Python) คือไลบรารีสำหรับคำนวณเชิงตัวเลขที่ทรงพลังที่สุดในวงการ Data Science — มี **array** เป็นโครงสร้างข้อมูลหลัก ที่:
- คำนวณกับข้อมูลทั้งชุดได้ในคำสั่งเดียว (ไม่ต้องเขียน loop เอง)
- เร็วกว่า list ปกติมาก (เพราะเขียนด้วยภาษา C อยู่ภายใน)
- เป็นพื้นฐานของไลบรารี Data Science อื่นๆ แทบทั้งหมด (pandas, scikit-learn, ฯลฯ)

### การติดตั้งและ import NumPy

ใน Google Colab มี NumPy ติดตั้งมาให้พร้อมใช้งานอยู่แล้ว ไม่ต้องติดตั้งเพิ่ม แค่ `import`


In [ ]:
import numpy as np   # np คือชื่อย่อที่ใช้กันเป็นมาตรฐานทั่วโลก

print(np.__version__)   # เช็คเวอร์ชันของ NumPy ที่ติดตั้งอยู่

2.0.2


---
## 2. การสร้าง Array

**array** ของ NumPy หน้าตาคล้าย list มาก แต่มีความสามารถเพิ่มขึ้นมาก (โดยเฉพาะการคำนวณ)

### 2.1 สร้าง array จาก list (วิธีที่ใช้บ่อยที่สุด)


In [ ]:
import numpy as np

scores_list = [78, 85, 62, 90, 55]    # list ปกติที่เรียนมา
scores_array = np.array(scores_list)    # แปลงเป็น NumPy array

print(scores_array)
print(type(scores_array))    # <class 'numpy.ndarray'>

[78 85 62 90 55]
<class 'numpy.ndarray'>


### 2.2 สร้าง array แบบ 2 มิติ (เหมือน nested list ที่เรียนมา)


In [ ]:
# nested list ที่เรียนมาจาก Collections (ตารางคะแนน 3 คน x 3 วิชา)
scores_nested_list = [
    [80, 90, 75],
    [60, 70, 65],
    [95, 88, 92],
]

scores_2d = np.array(scores_nested_list)
print(scores_2d)
print(type(scores_2d))

[[80 90 75]
 [60 70 65]
 [95 88 92]]
<class 'numpy.ndarray'>


### 2.3 ฟังก์ชันสร้าง array แบบสำเร็จรูป

NumPy มีฟังก์ชันช่วยสร้าง array รูปแบบที่ใช้บ่อยโดยไม่ต้องพิมพ์ค่าทีละตัว


In [ ]:
# np.zeros() - สร้าง array ที่มีค่า 0 ทั้งหมด
zeros_array = np.zeros(5)
print("zeros:", zeros_array)

# np.ones() - สร้าง array ที่มีค่า 1 ทั้งหมด
ones_array = np.ones(5)
print("ones:", ones_array)

# np.arange(start, stop, step) - เหมือน range() แต่ได้ array กลับมา (ไม่ต้องครอบ list())
range_array = np.arange(0, 10, 2)
print("arange:", range_array)

# np.linspace(start, stop, num) - สร้าง num ค่า กระจายเท่าๆกันระหว่าง start ถึง stop (รวมทั้งคู่)
linspace_array = np.linspace(0, 1, 5)
print("linspace:", linspace_array)

zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


---
## 3. Shape และมิติของ Array

**Shape** คือ "รูปร่าง" ของ array บอกว่ามีกี่แถว กี่คอลัมน์ (หรือกี่มิติ) — เป็นสิ่งที่ต้องเช็คบ่อยที่สุดเวลาทำงานกับ NumPy เพราะการคำนวณหลายอย่างต้องการ shape ที่ตรงกัน

| Attribute | ความหมาย |
|---|---|
| `.shape` | รูปร่างของ array เป็น tuple (เชื่อมกับ tuple ที่เรียนมา!) |
| `.ndim` | จำนวนมิติ (1D, 2D, 3D, ...) |
| `.size` | จำนวนสมาชิกทั้งหมด |
| `.dtype` | ชนิดข้อมูลของสมาชิกใน array |


In [ ]:
scores_1d = np.array([78, 85, 62, 90, 55])

print("shape:", scores_1d.shape)    # (5,) -- tuple ที่มีค่าเดียว (1 มิติ มี 5 ตัว)
print("ndim:", scores_1d.ndim)      # 1
print("size:", scores_1d.size)      # 5
print("dtype:", scores_1d.dtype)    # int64 (หรือ int32 ขึ้นกับระบบ)

In [ ]:
scores_2d = np.array([
    [80, 90, 75],
    [60, 70, 65],
    [95, 88, 92],
])

print("shape:", scores_2d.shape)    # (3, 3) -- 3 แถว 3 คอลัมน์
print("ndim:", scores_2d.ndim)      # 2
print("size:", scores_2d.size)      # 9 (3x3)

# unpack shape ด้วย tuple unpacking (เชื่อมกับเรื่อง tuple ที่เรียนมา)
rows, cols = scores_2d.shape
print(f"มี {rows} แถว, {cols} คอลัมน์")

### 3.1 `reshape()` — เปลี่ยนรูปร่าง array โดยไม่เปลี่ยนข้อมูล

ใช้บ่อยมากเวลาต้องปรับรูปร่างข้อมูลให้เข้ากับฟังก์ชัน/โมเดลที่ต้องการ shape เฉพาะแบบ


In [ ]:
numbers = np.arange(1, 13)   # array ของเลข 1-12 (1 มิติ มี 12 ตัว)
print("ก่อน reshape:", numbers)
print("shape ก่อน:", numbers.shape)

# เปลี่ยนเป็น 3 แถว 4 คอลัมน์ (3 x 4 = 12 พอดี ต้องคูณได้เท่ากับจำนวนสมาชิกเดิม)
numbers_2d = numbers.reshape(3, 4)
print("หลัง reshape เป็น (3,4):")
print(numbers_2d)

# เปลี่ยนเป็น 4 แถว 3 คอลัมน์ก็ได้ (4 x 3 = 12 เท่ากัน)
numbers_2d_v2 = numbers.reshape(4, 3)
print("หลัง reshape เป็น (4,3):")
print(numbers_2d_v2)

# ลอง reshape เป็นขนาดที่คูณกันไม่ได้ 12 -> จะ error
# numbers.reshape(3, 5)   # ลบ # แล้วรันดู จะเห็น ValueError

---
## 4. Vectorized Operation (การคำนวณแบบเวกเตอร์)

นี่คือจุดเด่นที่สุดของ NumPy — คำนวณกับสมาชิก**ทุกตัวใน array พร้อมกัน** ในคำสั่งเดียว โดยไม่ต้องเขียน loop เลย เรียกว่า **vectorized operation**

### 4.1 คำนวณกับค่าคงที่ (Scalar)


In [ ]:
scores = np.array([78, 85, 62, 90, 55])

# เทียบกับ list ที่บวกตรงๆไม่ได้ (ต้องใช้ comprehension) -- array ทำได้เลย!
print("บวก 5 ทุกตัว:", scores + 5)
print("คูณ 2 ทุกตัว:", scores * 2)
print("หารด้วย 10 ทุกตัว:", scores / 10)
print("ยกกำลัง 2 ทุกตัว:", scores ** 2)

# เทียบกับวิธีเดิมด้วย list comprehension
scores_list = [78, 85, 62, 90, 55]
scores_bonus_list = [s + 5 for s in scores_list]   # ต้องเขียน comprehension
scores_bonus_array = scores + 5                      # array ทำได้บรรทัดเดียว ไม่ต้อง loop
print(scores_bonus_list)
print(scores_bonus_array)

### 4.2 คำนวณระหว่าง array กับ array (element-wise)

เมื่อ array 2 ตัวมี shape ตรงกัน การคำนวณจะทำ "ทีละตำแหน่งที่ตรงกัน" (element-wise) อัตโนมัติ


In [ ]:
midterm = np.array([78, 85, 62, 90, 55])
final = np.array([82, 80, 70, 95, 60])

# บวกกันแบบ element-wise (ตำแหน่งที่ 0 บวกกับตำแหน่งที่ 0, ตำแหน่ง 1 บวกกับตำแหน่ง 1, ...)
total = midterm + final
print("รวมคะแนน:", total)

# หาค่าเฉลี่ยของแต่ละคน (เทียบกับ Notebook ก่อนหน้าที่ใช้ zip() กับ list ธรรมดา)
average = (midterm + final) / 2
print("เฉลี่ย:", average)

# เทียบ midterm กับ final ว่าใครทำข้อสอบ final ได้ดีขึ้น (ได้ array ของ True/False กลับมา)
improved = final > midterm
print("ทำได้ดีขึ้นไหม:", improved)

### 4.3 ฟังก์ชันสถิติพื้นฐานของ NumPy

NumPy มีฟังก์ชันคำนวณสถิติพื้นฐานในตัว เร็วกว่าเขียน loop เองมาก


In [ ]:
scores = np.array([78, 85, 62, 90, 55, 73, 88])

print("ผลรวม:", np.sum(scores))           # หรือ scores.sum()
print("ค่าเฉลี่ย:", np.mean(scores))       # หรือ scores.mean()
print("ค่าสูงสุด:", np.max(scores))        # หรือ scores.max()
print("ค่าต่ำสุด:", np.min(scores))        # หรือ scores.min()
print("ส่วนเบี่ยงเบนมาตรฐาน:", np.std(scores))   # standard deviation
print("ค่ามัธยฐาน:", np.median(scores))
print("เรียงลำดับ:", np.sort(scores))

### 4.4 Boolean Indexing — กรองข้อมูลด้วยเงื่อนไข (เชื่อมกับ if ที่เรียนมา)

จุดที่ทรงพลังมาก: ใส่เงื่อนไขเข้าไปใน `[]` ของ array เพื่อ "กรอง" เอาเฉพาะค่าที่ตรงเงื่อนไขออกมา — ทำงานคล้าย list comprehension ที่มี `if` แต่เร็วกว่ามากกับข้อมูลขนาดใหญ่


In [ ]:
scores = np.array([78, 85, 62, 90, 55, 73, 88])

# สร้าง boolean array จากเงื่อนไข (True/False ตามตำแหน่ง)
passing = scores >= 70
print("ผ่านไหม (boolean array):", passing)

# ใช้ boolean array นั้นกรองค่าออกมา (ได้เฉพาะค่าที่ True)
passing_scores = scores[scores >= 70]
print("คะแนนที่ผ่าน:", passing_scores)

# เทียบกับวิธีเดิมด้วย list comprehension
scores_list = [78, 85, 62, 90, 55, 73, 88]
passing_list = [s for s in scores_list if s >= 70]
print("เทียบกับ list comprehension:", passing_list)

# นับจำนวนคนที่ผ่าน
print("จำนวนคนที่ผ่าน:", np.sum(scores >= 70))   # True นับเป็น 1, False นับเป็น 0
print("เปอร์เซ็นต์คนที่ผ่าน:", np.mean(scores >= 70) * 100, "%")

---
## 5. การเข้าถึงและ Slicing Array 2 มิติ

Array 2 มิติเข้าถึงด้วย `array[แถว, คอลัมน์]` — สะดวกกว่า nested list ที่ต้องเขียน `list[แถว][คอลัมน์]` สองชั้น


In [ ]:
scores_2d = np.array([
    [80, 90, 75],   # นักศึกษาคนที่ 1
    [60, 70, 65],   # นักศึกษาคนที่ 2
    [95, 88, 92],   # นักศึกษาคนที่ 3
])

# เข้าถึงค่าตำแหน่งเดียว
print("แถว 0 คอลัมน์ 1:", scores_2d[0, 1])    # 90 (เทียบกับ nested_list[0][1])

# เข้าถึงทั้งแถว
print("แถวที่ 0 (นักศึกษาคนที่ 1) ทั้งหมด:", scores_2d[0])
print("แถวที่ 0 (เขียนแบบเต็ม):", scores_2d[0, :])    # ใส่ : หมายถึง "ทุกคอลัมน์"

# เข้าถึงทั้งคอลัมน์
print("คอลัมน์ที่ 1 (วิชาที่ 2) ทุกคน:", scores_2d[:, 1])    # ใส่ : หมายถึง "ทุกแถว"

# slicing แบบผสม
print("2 แถวแรก, 2 คอลัมน์แรก:")
print(scores_2d[0:2, 0:2])

แถว 0 คอลัมน์ 1: 90
แถวที่ 0 (นักศึกษาคนที่ 1) ทั้งหมด: [80 90 75]
แถวที่ 0 (เขียนแบบเต็ม): [80 90 75]
คอลัมน์ที่ 1 (วิชาที่ 2) ทุกคน: [90 70 88]
2 แถวแรก, 2 คอลัมน์แรก:
[[80 90]
 [60 70]]


In [ ]:
scores_2d[ 0 ,  [1,2]]

array([90, 75])

In [ ]:
scores_2d[[1,2], 1]

array([70, 88])

### 5.1 การคำนวณตามแถว/คอลัมน์ด้วย parameter `axis`

ฟังก์ชันสถิติของ NumPy (`sum`, `mean`, `max`, ...) คำนวณ "ทั้งหมด" โดย default แต่ระบุ `axis` เพื่อคำนวณเฉพาะตามแถวหรือคอลัมน์ได้

- `axis=0` → คำนวณ "ลงมาตามคอลัมน์" (ผลลัพธ์ 1 ค่าต่อคอลัมน์)
- `axis=1` → คำนวณ "ข้ามไปตามแถว" (ผลลัพธ์ 1 ค่าต่อแถว)


In [ ]:
scores_2d = np.array([
    [80, 90, 75],   # นักศึกษาคนที่ 1
    [60, 70, 65],   # นักศึกษาคนที่ 2
    [95, 88, 92],   # นักศึกษาคนที่ 3
])

print("ผลรวมทั้งหมด:", np.sum(scores_2d))             # รวมทุกตัว = 715

print("ผลรวมตามคอลัมน์ (axis=0):", np.sum(scores_2d, axis=0))   # รวมคะแนนแต่ละวิชา (ลงมา)
print("ผลรวมตามแถว (axis=1):", np.sum(scores_2d, axis=1))       # รวมคะแนนแต่ละคน (ข้าม)

print("เฉลี่ยแต่ละวิชา (axis=0):", np.mean(scores_2d, axis=0)) #axis = 0 เหลือแถวเดียว
print("เฉลี่ยแต่ละคน (axis=1):", np.mean(scores_2d, axis=1))

ผลรวมทั้งหมด: 715
ผลรวมตามคอลัมน์ (axis=0): [235 248 232]
ผลรวมตามแถว (axis=1): [245 195 275]
เฉลี่ยแต่ละวิชา (axis=0): [78.33333333 82.66666667 77.33333333]
เฉลี่ยแต่ละคน (axis=1): [81.66666667 65.         91.66666667]


> 💡 **เทคนิคจำ axis:** `axis=0` เดินตามแนวตั้ง (ดิ่งลง) ผลที่ได้คือ 1 ค่าต่อ**คอลัมน์** ส่วน `axis=1` เดินตามแนวนอน ผลที่ได้คือ 1 ค่าต่อ**แถว** — สับสนได้บ่อย ต้องลองรันดูผลลัพธ์เทียบกับ shape ของ array เสมอเวลาไม่แน่ใจ

### 5.2 สรุป: numpy array vs list ปกติ

| | list ปกติ | numpy array |
|---|---|---|
| คำนวณกับค่าคงที่ (`+`, `*`) | ❌ ทำตรงๆไม่ได้ ต้องใช้ comprehension | ✅ ทำได้ตรงๆ (vectorized) |
| ความเร็วกับข้อมูลจำนวนมาก | ช้ากว่า | เร็วกว่ามาก |
| เก็บข้อมูลคนละชนิดในตัวเดียว | ✅ ทำได้ | ❌ ควรเป็นชนิดเดียวกันทั้งหมด |
| ฟังก์ชันสถิติสำเร็จรูป | ❌ ไม่มี ต้องเขียนเอง | ✅ มีให้พร้อม (`mean`, `std`, ...) |
| ใช้กับ pandas/scikit-learn | ใช้ได้บางส่วน | ✅ เป็นพื้นฐานหลักของทั้งวงการ Data Science |


## Matrix

### การคำนวณเกี่ยวกับ Matrix

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [ ]:
# 1. การบวก/ลบ Matrix (Element-wise)
print("\nAddition (A + B):\n", A + B)
print("Subtraction (A - B):\n", A - B)


Addition (A + B):
 [[ 6  8]
 [10 12]]
Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]


In [ ]:
# 2. การคูณ Matrix
#   a) Element-wise multiplication (คูณกันทีละตำแหน่ง)
print("\nElement-wise Multiplication (A * B):\n", A * B)


Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]


In [ ]:
#   b) Matrix multiplication (Dot product) - ใช้ @ หรือ np.dot()
#      จำนวนคอลัมน์ของ Matrix แรกต้องเท่ากับจำนวนแถวของ Matrix หลัง
C = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
D = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

print("\nMatrix C (2x3):\n", C)
print("Matrix D (3x2):\n", D)

matrix_product = C @ D


Matrix C (2x3):
 [[1 2 3]
 [4 5 6]]
Matrix D (3x2):
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
# หรือ matrix_product = np.dot(C, D)
print("Matrix Multiplication (C @ D):\n", matrix_product)

Matrix Multiplication (C @ D):
 [[ 58  64]
 [139 154]]


In [ ]:
# 3. Transpose (สลับแถวเป็นคอลัมน์)
print("\nTranspose of A (A.T):\n", A.T)


Transpose of A (A.T):
 [[1 3]
 [2 4]]


In [ ]:
# 4. Determinant (ดีเทอร์มิแนนต์)
#    ใช้กับ Square Matrix (แถวเท่ากับคอลัมน์) เท่านั้น
print("\nDeterminant of A (np.linalg.det(A)):", np.linalg.det(A))


Determinant of A (np.linalg.det(A)): -2.0000000000000004


In [ ]:
# 5. Inverse Matrix (ผกผันของเมทริกซ์)
#    ใช้กับ Square Matrix ที่มี Determinant ไม่เท่ากับ 0 เท่านั้น
#    ผลลัพธ์ของ A @ A_inv ควรเป็น Identity Matrix
A_inv = np.linalg.inv(A)
print("\nInverse of A (np.linalg.inv(A)):\n", A_inv)
print("Check (A @ A_inv):\n", A @ A_inv) # ควรได้ Identity Matrix (มีค่าใกล้เคียง 1 ที่แนวทแยง)


Inverse of A (np.linalg.inv(A)):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Check (A @ A_inv):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### สร้าง Multidimensional Array (Matrix)

In [ ]:
# 2D array (Matrix)
matrix_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("2D Matrix (3x3):\n", matrix_2d)
print("Shape:", matrix_2d.shape)
print("ndim:", matrix_2d.ndim)

2D Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
ndim: 2


In [ ]:
# 3D array (Tensor)
# สร้าง 2 แผ่น (matrices) แต่ละแผ่นมีขนาด 2 แถว 3 คอลัมน์
matrix_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
print("\n3D Matrix (2x2x3):\n", matrix_3d)
print("Shape:", matrix_3d.shape)
print("ndim:", matrix_3d.ndim)


3D Matrix (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
ndim: 3


### ข้อ 1: NumPy — vectorized operation
มีคะแนนสอบ 2 วิชาเก็บเป็น NumPy array:
```python
quiz1 = np.array([8, 9, 6, 10, 7])
quiz2 = np.array([7, 10, 8, 9, 6])
```

จงคำนวณ (ใช้ vectorized operation ห้ามใช้ loop):
1. คะแนนรวมของทั้ง 2 quiz ของแต่ละคน
2. คะแนนเฉลี่ยของแต่ละคน
3. จำนวนคนที่คะแนนเฉลี่ย >= 8


In [ ]:
# เขียนคำตอบที่นี่
#1.คะแนนรวมของทั้ง 2 quiz ของแต่ละคน
#2. คะแนนเฉลี่ยของแต่ละคน
import numpy as np
quiz1 = np.array([8, 9, 6, 10, 7])
quiz2 = np.array([7, 10, 8, 9, 6])
total = quiz1 + quiz2
print("คะแนนรวมของแต่ละคน" , total)

คะแนนรวมของแต่ละคน [15 19 14 19 13]


In [ ]:
np.array([quiz1,quiz2]).mean(axis = 0)

array([7.5, 9.5, 7. , 9.5, 6.5])

In [ ]:
#3.จำนวนคนที่คะแนนเฉลี่ย >= 8
count_avg = np.array([quiz1,quiz2]).mean(axis = 0) >= 8
print("จำนวนคนที่มีคะแนนเฉลี่ย >= 8 คือ", count_avg.sum())

จำนวนคนที่มีคะแนนเฉลี่ย >= 8 คือ 2


### ข้อ 2: NumPy — 2D array และ axis
มีคะแนนสอบเก็บเป็น 2D array (4 คน x 3 วิชา):
```python
scores = np.array([
    [85, 70, 90],
    [60, 75, 65],
    [95, 88, 92],
    [55, 60, 58],
])
```

จงหา:
1. คะแนนเฉลี่ยของแต่ละวิชา (axis ไหน?)
2. คะแนนเฉลี่ยของแต่ละคน (axis ไหน?)
3. ใครได้คะแนนเฉลี่ยสูงสุด (Hint: ใช้ `np.mean(..., axis=...)` ร่วมกับ `np.argmax()` เพื่อหา index ของค่าสูงสุด)


In [10]:
# เขียนคำตอบที่นี่
import numpy as np
scores = np.array([
    [85, 70, 90],
    [60, 75, 65],
    [95, 88, 92],
    [55, 60, 58],
])


In [3]:
#คะแนนเฉลี่ยของแต่ละวิชา (axis ไหน?)
avg = np.mean(scores, axis=0)
print("คะแนนเฉลี่ยแต่ละวิชา (axis=0):", avg)

คะแนนเฉลี่ยแต่ละวิชา (axis=0): [73.75 73.25 76.25]


In [6]:
#คะแนนเฉลี่ยของแต่ละคน (axis ไหน?)
avg = np.mean(scores, axis=1)
print("คะแนนเฉลี่ยแต่ละคน (axis=1):", avg )

คะแนนเฉลี่ยแต่ละคน (axis=1): [81.66666667 66.66666667 91.66666667 57.66666667]


In [11]:
#ใครได้คะแนนเฉลี่ยสูงสุด
person_avg = np.mean(scores, axis=1)
best_index = np.argmax(person_avg)
print("คนที่ได้คะแนนเฉลี่ยสูงสุดคือ คนที่", best_index + 1, "ได้คะแนนเฉลี่ย", person_avg[best_index])

คนที่ได้คะแนนเฉลี่ยสูงสุดคือ คนที่ 3 ได้คะแนนเฉลี่ย 91.66666666666667


### ข้อ 3: ท้าทายเพิ่มเติม (Challenge) — รวม Function + OOP + NumPy
สร้าง class `Course` ที่มี:
1. `__init__(self, course_name)` — attribute `course_name` และ `scores` (list ว่างเริ่มต้น)
2. method `add_score(self, score)` — เพิ่มคะแนนเข้า `self.scores`
3. method `get_statistics(self)` — แปลง `self.scores` เป็น NumPy array แล้ว **return** dict ที่มี key: `mean`, `max`, `min`, `std` (ใช้ฟังก์ชัน NumPy ที่เรียนมา)
4. เขียนฟังก์ชัน `print_course_report(course)` (function ธรรมดา ไม่ใช่ method) ที่รับ object `Course` มา แล้ว print รายงานสรุปสถิติออกมาให้อ่านง่าย

ทดสอบสร้าง course เพิ่มคะแนน 5-6 ค่า แล้วเรียกดูรายงาน


In [14]:
# เขียนคำตอบที่นี่
import numpy as np
class Course:
    def __init__(self, course_name):
      self.course_name = course_name
      self.scores = []

    def add_score(self, score):
      self.scores.append(score)

    def get_statistics(self):
      scores_array = np.array(self.scores)
      return {
          "mean": np.mean(scores_array),
          "max": np.max(scores_array),
          "min": np.min(scores_array),
          "std": np.std(scores_array),
      }

def print_course_report(course):
    stats = course.get_statistics()
    print(f"===== รายงานสรุปวิชา: {course.course_name} =====")
    print(f"จำนวนคะแนนทั้งหมด : {len(course.scores)} ตัว")
    print(f"คะแนนทั้งหมด      : {course.scores}")
    print(f"คะแนนเฉลี่ย       : {stats['mean']:.2f}")
    print(f"คะแนนสูงสุด       : {stats['max']:.2f}")
    print(f"คะแนนต่ำสุด       : {stats['min']:.2f}")
    print(f"ส่วนเบี่ยงเบนมาตรฐาน (SD): {stats['std']:.2f}")
    print("=" * 45)

python_course = Course("Python Programming")
python_course.add_score(85)
python_course.add_score(90)
python_course.add_score(78)
python_course.add_score(92)
python_course.add_score(88)
python_course.add_score(75)

print_course_report(python_course)



===== รายงานสรุปวิชา: Python Programming =====
จำนวนคะแนนทั้งหมด : 6 ตัว
คะแนนทั้งหมด      : [85, 90, 78, 92, 88, 75]
คะแนนเฉลี่ย       : 84.67
คะแนนสูงสุด       : 92.00
คะแนนต่ำสุด       : 75.00
ส่วนเบี่ยงเบนมาตรฐาน (SD): 6.21


### ข้อ 4: ให้ใช้ loop ในการคำนวณผลรวมของแต่ละแถว (sum_row) และแต่ละหลัก (sum_col)

scores_2d = np.array([
    [80, 90, 75],   # นักศึกษาคนที่ 1
    [60, 70, 65],   # นักศึกษาคนที่ 2
    [95, 88, 92],   # นักศึกษาคนที่ 3
])

sum_row = [0, 0, 0]
sum_col = [0, 0, 0]
for i in range(len(scores_2d)):

In [12]:
# เขียนคำตอบที่นี่
scores_2d = np.array([
[80, 90, 75],   # นักศึกษาคนที่ 1
[60, 70, 65],   # นักศึกษาคนที่ 2
[95, 88, 92],   # นักศึกษาคนที่ 3
])

sum_row = [0, 0, 0]
sum_col = [0, 0, 0]

for r in range(scores_2d.shape[0]):
  for c in range(scores_2d.shape[1]):
      sum_row[r] += int(scores_2d[r, c])
      sum_col[c] += int(scores_2d[r, c])

print("ผลรวมแต่ละแถว/คน :", sum_row)
print("ผลรวมแต่ละหลัก/วิชา :", sum_col)

ผลรวมแต่ละแถว/คน : [245, 195, 275]
ผลรวมแต่ละหลัก/วิชา : [235, 248, 232]


---
## 🔗 เชื่อม Colab กับ GitHub

เก็บ Notebook นี้ขึ้น GitHub ต่อจากไฟล์ก่อนหน้า เพื่อให้ repo การเรียนของคุณสมบูรณ์ขึ้น

### วิธีที่ 1: เซฟจาก Colab ขึ้น GitHub ตรงๆ (ง่ายที่สุด)

1. ใน Colab ไปที่เมนู **File → Save a copy in GitHub**
2. เลือก repository เดิมที่ใช้เก็บ Notebook คาบก่อนๆ (เช่น `SC612104-coursework`)
3. ตั้งชื่อไฟล์และ commit message (เช่น `"เพิ่ม notebook: function, OOP, numpy"`) แล้วกด **OK**

### วิธีที่ 2: เปิด Notebook จาก GitHub เข้า Colab

1. ไปที่ **colab.research.google.com** → แท็บ **GitHub**
2. พิมพ์ชื่อ repo หรือ URL ของ Notebook บน GitHub แล้วเลือกไฟล์ที่ต้องการเปิด

### วิธีที่ 3: ใช้ Git ผ่าน Terminal

```bash
git clone https://github.com/<username>/<repo-name>.git
cd <repo-name>
git add notebook.ipynb
git commit -m "เพิ่ม notebook: function, OOP, numpy"
git push origin main
```